services:
  db:
    image: postgres:17
    container_name: contentflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: contentflow_user
      POSTGRES_PASSWORD: contentflow_password
      POSTGRES_DB: contentflow_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: